%% This .m file convert dat files generated by Andor Solis software into tif files. The .tif files are stored in the same folder as the one that contains the .dat files.
% v0: 2021-06-22, Allard A.

%% INPUT
% path: (string) folder that contains .dat files and acquisitionmetadata.ini

function dat2tif(path)

if nargin < 1 % If no path is specified, then ask user to select a folder
    path = uigetdir([],'Select a folder that contains .dat files and acquisitionmetadata.ini');
end

cd(path); % Change directory
paramfile = 'acquisitionmetadata.ini';
if ~exist(paramfile,'file')
    error('acquisitionmetadata.ini file is missing.')
end

list = ls('*.dat');
n = 0;
for j = 1:size(list,1)
    datfile = list(j,:);
    andorImage = readAndorDatImage(datfile,paramfile);
    for ii = 1:size(andorImage,3)
        n = n + 1;
        im = squeeze(andorImage(:,:,ii));
        tifname = strcat(num2str(n,'%06.f'),'.tif');
        imwrite(im,tifname)
    end
end

end
